export type WebConfigFormat = 'nginx' | 'traefik-file' | 'traefik-acme';

export type WebConfigInput = {
	name: string;
	serverNames: string[];
	certPem: string;
	keyPem: string;
	chainPem: string; // leaf + CA chain
	installDir: string; // path where files will live on the target server
	acmeEmail?: string;
};

export type WebConfigBundle = {
	files: Array<{name: string; content: string; mode?: number}>;
	primaryConfigName: string;
};

function safeSlug(s: string): string {
	return s.replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'cert';
}

function joinPosix(...parts: string[]): string {
	return parts
		.map((p, i) => (i === 0 ? p.replace(/\/+$/, '') : p.replace(/^\/+|\/+$/g, '')))
		.filter(Boolean)
		.join('/');
}

function nginxConfig(input: WebConfigInput, fileNames: {crt: string; key: string; chain: string}): string {
	const installDir = input.installDir.replace(/\/+$/, '');
	const certPath = joinPosix(installDir, fileNames.chain);
	const keyPath = joinPosix(installDir, fileNames.key);
	const names = input.serverNames.length ? input.serverNames.join(' ') : input.name;
	return [
		`# Generated by secutor for ${input.name}`,
		`# Place files in: ${installDir}`,
		``,
		`server {`,
		`    listen 443 ssl;`,
		`    listen [::]:443 ssl;`,
		`    http2 on;`,
		`    server_name ${names};`,
		``,
		`    ssl_certificate     ${certPath};`,
		`    ssl_certificate_key ${keyPath};`,
		``,
		`    ssl_protocols TLSv1.2 TLSv1.3;`,
		`    ssl_prefer_server_ciphers off;`,
		`    ssl_session_cache shared:SSL:10m;`,
		`    ssl_session_timeout 1d;`,
		``,
		`    # add_header Strict-Transport-Security "max-age=31536000" always;`,
		``,
		`    # location / {`,
		`    #     proxy_pass http://backend;`,
		`    #     proxy_set_header Host $host;`,
		`    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
		`    #     proxy_set_header X-Forwarded-Proto $scheme;`,
		`    # }`,
		`}`,
		``,
		`# HTTP -> HTTPS redirect (optional)`,
		`# server {`,
		`#     listen 80;`,
		`#     listen [::]:80;`,
		`#     server_name ${names};`,
		`#     return 301 https://$host$request_uri;`,
		`# }`,
		``,
	].join('\n');
}

function traefikFileConfig(input: WebConfigInput, fileNames: {crt: string; key: string; chain: string}): string {
	const installDir = input.installDir.replace(/\/+$/, '');
	const certPath = joinPosix(installDir, fileNames.chain);
	const keyPath = joinPosix(installDir, fileNames.key);
	const slug = safeSlug(input.name);
	const host = input.serverNames[0] || input.name;
	const extraSans = input.serverNames.slice(1);
	const rule =
		input.serverNames.length > 1
			? `Host(${input.serverNames.map(s => `\`${s}\``).join(', ')})`
			: `Host(\`${host}\`)`;
	const sansBlock = extraSans.length
		? [`      subjectAlternativeNames:`, ...extraSans.map(s => `        - "${s}"`)]
		: [];
	return [
		`# Generated by secutor for ${input.name}`,
		`# Traefik dynamic config (file provider).`,
		`# Reference from traefik static config:`,
		`#   providers:`,
		`#     file:`,
		`#       filename: /etc/traefik/${slug}.dynamic.yml`,
		`#       watch: true`,
		``,
		`tls:`,
		`  certificates:`,
		`    - certFile: ${certPath}`,
		`      keyFile:  ${keyPath}`,
		...sansBlock,
		`      stores:`,
		`        - default`,
		``,
		`http:`,
		`  routers:`,
		`    ${slug}:`,
		`      rule: "${rule}"`,
		`      entryPoints:`,
		`        - websecure`,
		`      service: ${slug}`,
		`      tls: {}`,
		`  services:`,
		`    ${slug}:`,
		`      loadBalancer:`,
		`        servers:`,
		`          - url: "http://backend:8080"`,
		``,
	].join('\n');
}

function traefikAcmeStatic(input: WebConfigInput): string {
	const email = input.acmeEmail || `admin@${input.serverNames[0] || 'example.com'}`;
	return [
		`# Generated by secutor for ${input.name}`,
		`# Traefik static config with ACME (Let's Encrypt) + file provider fallback.`,
		``,
		`entryPoints:`,
		`  web:`,
		`    address: ":80"`,
		`    http:`,
		`      redirections:`,
		`        entryPoint:`,
		`          to: websecure`,
		`          scheme: https`,
		`  websecure:`,
		`    address: ":443"`,
		``,
		`certificatesResolvers:`,
		`  letsencrypt:`,
		`    acme:`,
		`      email: "${email}"`,
		`      storage: /etc/traefik/acme.json`,
		`      httpChallenge:`,
		`        entryPoint: web`,
		``,
		`providers:`,
		`  file:`,
		`    filename: /etc/traefik/${safeSlug(input.name)}.dynamic.yml`,
		`    watch: true`,
		``,
		`# api:`,
		`#   dashboard: true`,
		``,
	].join('\n');
}

function traefikAcmeDynamic(input: WebConfigInput, fileNames: {crt: string; key: string; chain: string}): string {
	const installDir = input.installDir.replace(/\/+$/, '');
	const certPath = joinPosix(installDir, fileNames.chain);
	const keyPath = joinPosix(installDir, fileNames.key);
	const slug = safeSlug(input.name);
	const host = input.serverNames[0] || input.name;
	const rule =
		input.serverNames.length > 1
			? `Host(${input.serverNames.map(s => `\`${s}\``).join(', ')})`
			: `Host(\`${host}\`)`;
	return [
		`# Generated by secutor for ${input.name} (dynamic, ACME + file fallback)`,
		``,
		`http:`,
		`  routers:`,
		`    ${slug}:`,
		`      rule: "${rule}"`,
		`      entryPoints:`,
		`        - websecure`,
		`      service: ${slug}`,
		`      tls:`,
		`        certResolver: letsencrypt`,
		`  services:`,
		`    ${slug}:`,
		`      loadBalancer:`,
		`        servers:`,
		`          - url: "http://backend:8080"`,
		``,
		`# Local certificate fallback (used until ACME issues one)`,
		`tls:`,
		`  certificates:`,
		`    - certFile: ${certPath}`,
		`      keyFile:  ${keyPath}`,
		`      stores:`,
		`        - default`,
		``,
	].join('\n');
}

export function buildWebConfig(fmt: WebConfigFormat, input: WebConfigInput): WebConfigBundle {
	const slug = safeSlug(input.name);
	const fileNames = {
		crt: `${slug}.crt`,
		key: `${slug}.key`,
		chain: `${slug}-chain.crt`,
	};
	const certFiles: WebConfigBundle['files'] = [
		{name: fileNames.crt, content: input.certPem},
		{name: fileNames.key, content: input.keyPem, mode: 0o600},
		{name: fileNames.chain, content: input.chainPem},
	];
	if (fmt === 'nginx') {
		const conf = `${slug}.conf`;
		return {
			primaryConfigName: conf,
			files: [...certFiles, {name: conf, content: nginxConfig(input, fileNames)}],
		};
	}
	if (fmt === 'traefik-file') {
		const conf = `${slug}.dynamic.yml`;
		return {
			primaryConfigName: conf,
			files: [...certFiles, {name: conf, content: traefikFileConfig(input, fileNames)}],
		};
	}
	// traefik-acme
	const staticName = `traefik.yml`;
	const dynamicName = `${slug}.dynamic.yml`;
	return {
		primaryConfigName: staticName,
		files: [
			...certFiles,
			{name: staticName, content: traefikAcmeStatic(input)},
			{name: dynamicName, content: traefikAcmeDynamic(input, fileNames)},
		],
	};
}

export function bundleAsText(bundle: WebConfigBundle): string {
	const sep = '\n# ============================================================\n';
	return bundle.files
		.map(f => `# === FILE: ${f.name} ===\n${f.content}`)
		.join(sep);
}
